# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                # not secured at all: passwords not encrypted
                # also, users have to be loaded from database where they are already stocked
                # these are only meant as tests
                coucou:
                  password: coucou
                  roles: 'ROLE_USER'
                admin:
                  password: admin
                  roles: 'ROLE_ADMIN'

    encoders:
        # this doesn't encode passwords
        Symfony\Component\Security\Core\User\User: plaintext
        # this does
        #Symfony\Component\Security\Core\User\User:
            #algorithm: bcrypt
            #cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
              login_path: authentication
              check_path: authentication
              default_target_path: search
              always_use_default_target_path: true

            logout_on_user_change: true

        secured_area:
            form_login:
              csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout/
                target: /

            logout_on_user_change: true

    # prevents unauthenticated from accessing pages beyond "/auth/"
    access_control:
        - { path: ^/authentication$, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/(search|agent), roles: IS_AUTHENTICATED_FULLY }
